### ISSUE TITLE
field with diff service is not persistent

### ISSUE THREAD

**Issue by judovana** [jenkinsci/report-jtreg-plugin#32]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

all

### Reproduction steps

turn of jenkins
start on jekins

the url to diff service is gone (and all links conditionaly missing)

### Expected Results

the diff services url will  persist restart

### Actual Results

diff url do not persists restart

**Comment by patrikcerbak** [comment]
I renamed the variable which holds this information, so with the upgrade of the plugin, the value which was set was lost. However, with just a restart of Jenkins, the value should still be there. It works correctly on my local environment.
